version: '3.9'

# Backend-only services for local development
# Use this when running Next.js locally (pnpm dev)

services:
  postgres:
    image: postgres:16-alpine
    container_name: betterbros-postgres
    environment:
      POSTGRES_DB: betterbros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: betterbros-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    container_name: betterbros-api
    ports:
      - '8000:8000'
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/betterbros

      # Redis
      REDIS_URL: redis://redis:6379

      # Auth (using supabase for dev)
      AUTH_PROVIDER: supabase
      SUPABASE_JWT_SECRET: dummy_secret_for_dev

      # API Keys (from your .env file)
      ODDS_API_KEY: ${ODDS_API_KEY:-}
      SPORTGAMEODDS_API_KEY: ${SPORTGAMEODDS_API_KEY:-}
      SLEEPER_API_KEY: ${SLEEPER_API_KEY:-}
      OPENWEATHER_KEY: ${OPENWEATHER_KEY:-}

      # Environment
      ENVIRONMENT: development
      LOG_LEVEL: INFO

    volumes:
      - ../apps/api:/app/apps/api
      - ../data:/app/data
      - ../exports:/app/exports
      - ../experiments:/app/experiments
      - ../shares:/app/shares
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
