version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: betterbros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/betterbros
      REDIS_URL: redis://redis:6379
    volumes:
      - ../apps/api:/app/apps/api
      - ../data:/app/data
      - ../exports:/app/exports
      - ../experiments:/app/experiments
      - ../shares:/app/shares
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_BASE: http://api:8000
    volumes:
      - ../apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - /app/node_modules
    depends_on:
      - api
    command: pnpm --filter web dev

volumes:
  postgres_data:
  redis_data:
