/**
 * Mock data for testing the UI without a backend
 * Showcases all supported sports and stat types
 */

import type { Sport, StatType } from './types/stats';

export interface MockProp {
  id: string;
  sport: Sport;
  player: string;
  team: string;
  opponent: string;
  game_time: string;
  stat_type: StatType;
  line: number;
  over_odds: number;
  under_odds: number;
  market: string;
  ev: number;
  confidence: number;
  projection: number;
  is_live: boolean;
  position?: string;
}

export const mockProps: MockProp[] = [
  // ========== NFL Props ==========
  {
    id: 'nfl-1',
    sport: 'NFL',
    player: 'Patrick Mahomes',
    team: 'KC',
    position: 'QB',
    opponent: 'vs BUF',
    game_time: '2024-01-15T20:00:00',
    stat_type: 'Passing Yards',
    line: 275.5,
    over_odds: -110,
    under_odds: -110,
    market: 'PrizePicks',
    ev: 8.2,
    confidence: 87,
    projection: 295.3,
    is_live: true,
  },
  {
    id: 'nfl-2',
    sport: 'NFL',
    player: 'Josh Allen',
    team: 'BUF',
    position: 'QB',
    opponent: '@ KC',
    game_time: '2024-01-15T20:00:00',
    stat_type: 'Pass + Rush Yards',
    line: 285.5,
    over_odds: +105,
    under_odds: -125,
    market: 'Underdog',
    ev: 7.3,
    confidence: 84,
    projection: 305.2,
    is_live: true,
  },
  {
    id: 'nfl-3',
    sport: 'NFL',
    player: 'Fred Warner',
    team: 'SF',
    position: 'LB',
    opponent: '@ GB',
    game_time: '2024-01-15T16:30:00',
    stat_type: 'Total Tackles',
    line: 8.5,
    over_odds: -115,
    under_odds: -105,
    market: 'PrizePicks',
    ev: 6.1,
    confidence: 81,
    projection: 10.2,
    is_live: false,
  },
  {
    id: 'nfl-4',
    sport: 'NFL',
    player: 'Tyreek Hill',
    team: 'MIA',
    position: 'WR',
    opponent: 'vs NYJ',
    game_time: '2024-01-15T13:00:00',
    stat_type: 'Receiving Yards',
    line: 85.5,
    over_odds: -115,
    under_odds: -105,
    market: 'PrizePicks',
    ev: 5.8,
    confidence: 79,
    projection: 96.2,
    is_live: false,
  },
  {
    id: 'nfl-5',
    sport: 'NFL',
    player: 'Christian McCaffrey',
    team: 'SF',
    position: 'RB',
    opponent: '@ GB',
    game_time: '2024-01-15T16:30:00',
    stat_type: 'Rush + Rec Yards',
    line: 125.5,
    over_odds: -110,
    under_odds: -110,
    market: 'Underdog',
    ev: 4.9,
    confidence: 76,
    projection: 138.4,
    is_live: false,
  },
  {
    id: 'nfl-6',
    sport: 'NFL',
    player: 'Justin Tucker',
    team: 'BAL',
    position: 'K',
    opponent: 'vs PIT',
    game_time: '2024-01-15T13:00:00',
    stat_type: 'Kicking Points',
    line: 7.5,
    over_odds: -105,
    under_odds: -115,
    market: 'PrizePicks',
    ev: 3.2,
    confidence: 72,
    projection: 9.0,
    is_live: false,
  },
  {
    id: 'nfl-7',
    sport: 'NFL',
    player: 'Micah Parsons',
    team: 'DAL',
    position: 'LB',
    opponent: 'vs PHI',
    game_time: '2024-01-15T16:30:00',
    stat_type: 'Solo Tackles',
    line: 4.5,
    over_odds: +100,
    under_odds: -120,
    market: 'Underdog',
    ev: 2.8,
    confidence: 69,
    projection: 5.3,
    is_live: false,
  },

  // ========== NBA Props ==========
  {
    id: 'nba-1',
    sport: 'NBA',
    player: 'Luka Doncic',
    team: 'DAL',
    position: 'PG',
    opponent: 'vs LAL',
    game_time: '2024-01-15T22:30:00',
    stat_type: 'Points',
    line: 31.5,
    over_odds: -110,
    under_odds: -110,
    market: 'PrizePicks',
    ev: 9.1,
    confidence: 88,
    projection: 35.2,
    is_live: false,
  },
  {
    id: 'nba-2',
    sport: 'NBA',
    player: 'Nikola Jokic',
    team: 'DEN',
    position: 'C',
    opponent: '@ PHX',
    game_time: '2024-01-15T21:00:00',
    stat_type: 'Triple Double',
    line: 0.5,
    over_odds: +150,
    under_odds: -180,
    market: 'Underdog',
    ev: 8.7,
    confidence: 65,
    projection: 0.42,
    is_live: false,
  },
  {
    id: 'nba-3',
    sport: 'NBA',
    player: 'Anthony Davis',
    team: 'LAL',
    position: 'PF',
    opponent: '@ DAL',
    game_time: '2024-01-15T22:30:00',
    stat_type: 'Rebounds',
    line: 11.5,
    over_odds: -105,
    under_odds: -115,
    market: 'PrizePicks',
    ev: 7.2,
    confidence: 83,
    projection: 13.1,
    is_live: false,
  },
  {
    id: 'nba-4',
    sport: 'NBA',
    player: 'Trae Young',
    team: 'ATL',
    position: 'PG',
    opponent: 'vs BOS',
    game_time: '2024-01-15T19:30:00',
    stat_type: 'Assists',
    line: 9.5,
    over_odds: -110,
    under_odds: -110,
    market: 'Underdog',
    ev: 5.4,
    confidence: 77,
    projection: 10.8,
    is_live: true,
  },
  {
    id: 'nba-5',
    sport: 'NBA',
    player: 'Giannis Antetokounmpo',
    team: 'MIL',
    position: 'PF',
    opponent: 'vs MIA',
    game_time: '2024-01-15T20:00:00',
    stat_type: 'Double Double',
    line: 0.5,
    over_odds: -250,
    under_odds: +200,
    market: 'PrizePicks',
    ev: 4.8,
    confidence: 92,
    projection: 0.87,
    is_live: false,
  },
  {
    id: 'nba-6',
    sport: 'NBA',
    player: 'Stephen Curry',
    team: 'GSW',
    position: 'PG',
    opponent: '@ LAC',
    game_time: '2024-01-15T22:00:00',
    stat_type: '1st Quarter Points',
    line: 7.5,
    over_odds: -105,
    under_odds: -115,
    market: 'Underdog',
    ev: 3.9,
    confidence: 71,
    projection: 8.4,
    is_live: false,
  },

  // ========== MLB Props ==========
  {
    id: 'mlb-1',
    sport: 'MLB',
    player: 'Shohei Ohtani',
    team: 'LAD',
    position: 'DH',
    opponent: 'vs SD',
    game_time: '2024-07-20T19:10:00',
    stat_type: 'Total Bases',
    line: 1.5,
    over_odds: +105,
    under_odds: -125,
    market: 'PrizePicks',
    ev: 8.9,
    confidence: 82,
    projection: 2.3,
    is_live: false,
  },
  {
    id: 'mlb-2',
    sport: 'MLB',
    player: 'Gerrit Cole',
    team: 'NYY',
    position: 'SP',
    opponent: '@ BOS',
    game_time: '2024-07-20T19:10:00',
    stat_type: 'Strikeouts',
    line: 6.5,
    over_odds: -110,
    under_odds: -110,
    market: 'Underdog',
    ev: 7.5,
    confidence: 84,
    projection: 7.8,
    is_live: false,
  },
  {
    id: 'mlb-3',
    sport: 'MLB',
    player: 'Aaron Judge',
    team: 'NYY',
    position: 'RF',
    opponent: '@ BOS',
    game_time: '2024-07-20T19:10:00',
    stat_type: 'Home Runs',
    line: 0.5,
    over_odds: +180,
    under_odds: -220,
    market: 'PrizePicks',
    ev: 6.8,
    confidence: 34,
    projection: 0.38,
    is_live: false,
  },
  {
    id: 'mlb-4',
    sport: 'MLB',
    player: 'Freddie Freeman',
    team: 'LAD',
    position: '1B',
    opponent: 'vs SD',
    game_time: '2024-07-20T19:10:00',
    stat_type: 'Hits',
    line: 1.5,
    over_odds: -105,
    under_odds: -115,
    market: 'Underdog',
    ev: 4.2,
    confidence: 73,
    projection: 1.9,
    is_live: false,
  },
  {
    id: 'mlb-5',
    sport: 'MLB',
    player: 'Spencer Strider',
    team: 'ATL',
    position: 'SP',
    opponent: 'vs PHI',
    game_time: '2024-07-20T19:20:00',
    stat_type: 'Outs',
    line: 16.5,
    over_odds: -110,
    under_odds: -110,
    market: 'PrizePicks',
    ev: 3.7,
    confidence: 75,
    projection: 18.2,
    is_live: false,
  },

  // ========== NHL Props ==========
  {
    id: 'nhl-1',
    sport: 'NHL',
    player: 'Connor McDavid',
    team: 'EDM',
    position: 'C',
    opponent: 'vs COL',
    game_time: '2024-03-15T21:00:00',
    stat_type: 'Points',
    line: 1.5,
    over_odds: -105,
    under_odds: -115,
    market: 'PrizePicks',
    ev: 9.3,
    confidence: 86,
    projection: 2.1,
    is_live: false,
  },
  {
    id: 'nhl-2',
    sport: 'NHL',
    player: 'Auston Matthews',
    team: 'TOR',
    position: 'C',
    opponent: '@ BOS',
    game_time: '2024-03-15T19:00:00',
    stat_type: 'Goals',
    line: 0.5,
    over_odds: +120,
    under_odds: -140,
    market: 'Underdog',
    ev: 7.8,
    confidence: 48,
    projection: 0.72,
    is_live: false,
  },
  {
    id: 'nhl-3',
    sport: 'NHL',
    player: 'Igor Shesterkin',
    team: 'NYR',
    position: 'G',
    opponent: 'vs NJD',
    game_time: '2024-03-15T19:00:00',
    stat_type: 'Saves',
    line: 27.5,
    over_odds: -110,
    under_odds: -110,
    market: 'PrizePicks',
    ev: 5.9,
    confidence: 79,
    projection: 30.2,
    is_live: false,
  },
  {
    id: 'nhl-4',
    sport: 'NHL',
    player: 'Nathan MacKinnon',
    team: 'COL',
    position: 'C',
    opponent: '@ EDM',
    game_time: '2024-03-15T21:00:00',
    stat_type: 'Power Play Points',
    line: 0.5,
    over_odds: +140,
    under_odds: -160,
    market: 'Underdog',
    ev: 4.3,
    confidence: 42,
    projection: 0.58,
    is_live: false,
  },
  {
    id: 'nhl-5',
    sport: 'NHL',
    player: 'Cale Makar',
    team: 'COL',
    position: 'D',
    opponent: '@ EDM',
    game_time: '2024-03-15T21:00:00',
    stat_type: 'Blocked Shots',
    line: 2.5,
    over_odds: -105,
    under_odds: -115,
    market: 'PrizePicks',
    ev: 3.1,
    confidence: 68,
    projection: 3.2,
    is_live: false,
  },
];

export const mockTrendingProps = [
  { label: 'High EV (>5%)', count: 28, color: 'profit', sport: null },
  { label: 'Live Now', count: 3, color: 'live', sport: null },
  { label: 'NFL Props', count: 7, color: 'primary', sport: 'NFL' },
  { label: 'NBA Props', count: 6, color: 'primary', sport: 'NBA' },
  { label: 'MLB Props', count: 5, color: 'secondary', sport: 'MLB' },
  { label: 'NHL Props', count: 5, color: 'secondary', sport: 'NHL' },
  { label: 'Tackles & Defense', count: 4, color: 'default', sport: 'NFL' },
  { label: 'Double-Doubles', count: 3, color: 'default', sport: 'NBA' },
  { label: 'Strikeouts', count: 2, color: 'default', sport: 'MLB' },
  { label: 'Power Play Points', count: 2, color: 'default', sport: 'NHL' },
];

export const mockCalibration = {
  overall_accuracy: 73.2,
  total_tracked: 1247,
  by_confidence_level: [
    { level: '80-100%', accuracy: 81.5, count: 156 },
    { level: '60-80%', accuracy: 72.3, count: 487 },
    { level: '40-60%', accuracy: 58.9, count: 604 },
  ],
};
